In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/20200524_L.csv',index_col=0)

In [3]:
la, v = np.linalg.eig(df.values)

In [4]:
for i in range(len(la)):
    print('第'+str(i)+'成分')
    print(la[i])
    print(v[i])

第0成分
0.9999999999999993
[-0.81649658  0.57735027 -0.32444284  0.          0.        ]
第1成分
3.999999999999999
[ 0.40824829  0.57735027 -0.48666426  0.          0.        ]
第2成分
0.9999999999999998
[0.40824829 0.57735027 0.81110711 0.         0.        ]
第3成分
2.0
[ 0.          0.          0.          0.70710678 -0.70710678]
第4成分
0.0
[0.         0.         0.         0.70710678 0.70710678]


array([ 0.35355339, -0.35355339, -0.35355339,  0.70710678, -0.35355339])